### ISSUE TITLE
Nefunkcni v Kodi 19 Matrix

### ISSUE THREAD

**Issue by Kisuke-CZE** [koudi/plugin.video.mall.tv#18]
Plugin nefunguje v Kodi Matrix

Prvne ma v `addon.xml` zavislost na python 2 - Od Kodi Matrix je vsak podporovan jen Python 3. Zkousel sem zatim jen tu zavislost odparat, ale narazil sem na druhy zasadnejsi problem.

Druhym hlavnim problemem je, ze v Kodi 19 jiz neni pritomen modul `kodiswift`, ktery tento plugin vyuziva.

**Comment by mikromCZ** [comment]
Postupoval a skončil jsem stejně. Je to poslední doplněk co mi chybí ke štěstí ☺

**Comment by kapitan-iglu** [comment]
njn, raz to muselo prist :-/ Blba je ta chybajuca kodiswift-v19-kompatibilna kniznica, na ktorej je cely plugin postaveny... Aj [tu](https://forum.kodi.tv/showthread.php?tid=353398) aj [tu](https://github.com/afrase/kodiswift/issues) zdochol pes... Cakal (a dufal) som, ze autor zapracuje potrebne zmeny no zatial sa tak nestalo. Neviem ci este pockat (toto nie je jediny plugin postaveny na kodiswift a uvolnenie v19 by malo vecami zahybat) alebo sa rovno pustit do prepisovania, co zas nebude na chvilu...

**Comment by Kisuke-CZE** [comment]
Castecne se mi to povedlo rozchodit zde:

https://github.com/Kisuke-CZE/plugin.video.mall.tv/commit/4b23f0d58b9058d8cf3bd06d6333bd3182edbf3e

Problem ale je, ze se v menu neukazujou popisky, a nefunguje polozka nejnovejsi porady, konci chybou:
```
2021-03-01 18:57:02.944 T:3644    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: from_dict() got an unexpected keyword argument 'link'
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi19L/.kodi/addons/plugin.video.mall.tv/addon.py", line 94, in <module>
                                                       plugin.run()
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 321, in _dispatch
                                                       listitems = self.finish(listitems)
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 474, in finish
                                                       self.add_items(items)
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 390, in add_items
                                                       _items = [self._listitemify(item) for item in items]
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 390, in <listcomp>
                                                       _items = [self._listitemify(item) for item in items]
                                                     File "/opt/Kodi19L/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 297, in _listitemify
                                                       item = ListItem.from_dict(**item)
                                                   TypeError: from_dict() got an unexpected keyword argument 'link'
                                                   -->End of Python script error report<--


```

**Comment by kapitan-iglu** [comment]
xbmcswift2 znie nadejne, kuknem sa na to.

**Comment by Kisuke-CZE** [comment]
Jeste se mi podarilo prevest ti puvodni knihovnu kodiswift pomoci nastroje 2to3.

Zda se ze po jeji instalaci to fungue uplne stejne spatne jako s tou knihovnou xbmcswift2. 

[script.module.kodiswift.zip](https://github.com/koudi/plugin.video.mall.tv/files/6064251/script.module.kodiswift.zip)

**Comment by kapitan-iglu** [comment]
Zakladna verzia pre v19 prehravajuca videa je zatial vo vetve [migrate2matrix](../tree/migrate2matrix), priebezne to budem dokoncovat. Vyskusajte rucne nainstalovat zo [zipu](../archive/migrate2matrix.zip).

Videa sice prehrava, ale nezobrazuje thubnaily. Nahlaste dalsie nedostatky, ktore objavite.
Tiez som si vsimol, ze niektore videa (hlavne live) vytimeoutuju zo strany CDN (ale to robi aj stara verzia v starom kodi).

**Comment by Kisuke-CZE** [comment]
Dik. Za me super - dela to co ma.
Thumbnaily mi neukazuje ani stara verze v Kodi 18, a ani sem se po nich nikdy neshanel.

**Comment by kapitan-iglu** [comment]
Thumbnaily a fanarty opravene [v1.0.1](https://github.com/koudi/plugin.video.mall.tv/tree/2db99021880cc3dcd526de950d88f7483badd644).

**Comment by jbrepogmailcom** [comment]
Ahoj, mohu poprosit o návod pro laika jak instalovat? Standardní postup je stáhnout si doplněk v KODI 19 přes instalace doplňků nebo repository. Pokud vývojář očekává, že běžný uživatel bude stahovat soubory .py a připojovat se na KODI přes ssh a hledat, do jakého adresáře je vložit přes scp, pak asi moc úspěch mít nebude :-)

**Comment by mikromcz** [comment]
> Ahoj, mohu poprosit o návod pro laika jak instalovat? Standardní postup je stáhnout si doplněk v KODI 19 přes instalace doplňků nebo repository. Pokud vývojář očekává, že běžný uživatel bude stahovat soubory .py a připojovat se na KODI přes ssh a hledat, do jakého adresáře je vložit přes scp, pak asi moc úspěch mít nebude :-)

A stáhnout zip zde z gitu (nebo z odkazu na fóru) a nainstalovat z něj?
