### ISSUE TITLE
mall.tv přestal fungovat, Error Contents: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by jbrepogmailcom** [koudi/plugin.video.mall.tv#19]
Ahoj, už několik týdnů mi plugin v KODI nefunguje, dostávám tuto chybovou hlášku:

```
2021-04-16 21:25:25.110 T:140307005486848 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
2021-04-16 21:25:25.113 T:140307005486848  NOTICE: [kodiswift] Request for "/video/%2Fudalosti-ludka-stanka%2Fneni-cim-ockovat-hamacek-to-zaridi-aneb-cesko-jako-farmaceuticky-bufetak" matches rule for function "video"
2021-04-16 21:25:25.504 T:140307005486848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'string'
                                            Traceback (most recent call last):
                                              File "/home/janbenes/.kodi/addons/plugin.video.mall.tv/addon.py", line 94, in <module>
                                                plugin.run()
                                              File "/home/janbenes/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/janbenes/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/home/janbenes/.kodi/addons/plugin.video.mall.tv/addon.py", line 30, in video
                                                url = api.get_video_url(link)
                                              File "/home/janbenes/.kodi/addons/plugin.video.mall.tv/mall.py", line 293, in get_video_url
                                                main_link = self.get_video_main_url(page)
                                              File "/home/janbenes/.kodi/addons/plugin.video.mall.tv/mall.py", line 283, in get_video_main_url
                                                tmp_str = re.sub(r'^.*VideoSource"[\s]*:[\s]*"', '', script_tag.string.encode('utf-8'))
                                            AttributeError: 'NoneType' object has no attribute 'string'
                                            -->End of Python script error report<--
2021-04-16 21:25:25.551 T:140307948344192   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2Fudalosti-ludka-stanka%2Fneni-cim-ockovat-hamacek-to-zaridi-aneb-cesko-jako-farmaceuticky-bufetak]
```

**Comment by kapitan-iglu** [comment]
Ahoj,
aku verziu pluginu a kodi mas? Nemoze to suvisiet s #18?

**Comment by jbrepogmailcom** [comment]
Ahoj, Mám verzi KODI Leia 18 a plugin 0.0.15, RasPi4 a LibreELEC. mall.tv plugin fungoval do doby asi před měsícem, pak nefungoval vůbec a když jsem jej ručně smazal z disku přes ssh včetně dat a nainstaloval znova tak šel aspoň spustit. Nicméně nyní se nenačtou na preview obrázky a při pokusu o spuštění jen vyskočí hláška že to nejde a víc detailů v logu.

Log taky ukazuje na plugin kodiswift, ten jsem smazal a nainstaloval znova ale nepomohlo to. Co se týká issue #18, zdá se, že ta chyba co je tady v kodiswift je tam v xbmcswift2 v KODI19.

**Comment by kapitan-iglu** [comment]
Aku verziu kodiswift mas? [Tu sme riesili](https://www.xbmc-kodi.cz/prispevek-mall-tv?pid=96859#pid96859), ze docasne existovala chybna verzia 0.0.9, funguje az 0.0.10+.

A este pre istotu, aku verziu pluginu BeautifulSoup4 mas? V rovnakom case ako pises [sa objavil](https://www.xbmc-kodi.cz/prispevek-mall-tv?pid=100149#pid100149) novy problem.

O [nefunkcnych thumbnailoch viem](https://www.xbmc-kodi.cz/prispevek-mall-tv?pid=99522#pid99522), zmena na strane mall.tv, opavim.

**Comment by jbrepogmailcom** [comment]
kodiswift 0.0.11 a BeautifulSoup4 4.9.3.  S BS jsem měl myslím problém dřív a musel jsem to smazat ručně a nainstalovat znovu

**Comment by kapitan-iglu** [comment]
Asi tusim kde bude chyba. Skus downgradovat BeautifulSoup4 na verziu 4.6.2. Cez vlastnosti doplnku mall.tv -> zavislosti -> BeautifulSoup4 ->vypni automaticku aktualizaciu -> aktualizovat -> 4.6.2. Ak nema kodi nacacheovanu starsiu verziu, tak ju stiahni z [offic repa](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/).

Podari sa ti potom prehrat Ludka?

**Comment by jbrepogmailcom** [comment]
Výborně, downgrade pomohl, děkuji! Nevím jestli je nějaký jednoduchý postup na downgrade, ale musel jsem stáhnout beautifulsoup zip a nainstallovat addon ze zip souboru a pak zakázat automatické aktualizace.

**Comment by kapitan-iglu** [comment]
V tom pripade to bolo sposobene nekompatibilitou, ktoru som opravil vo verzii 0.0.16. Mozes povolit automaticky update aj BeautifulSoap4 aj mall.tv.

Postup na downgrade popisany vyssie ti nefungoval?
>  Cez vlastnosti doplnku mall.tv -> zavislosti -> BeautifulSoup4 -> vypni automaticku aktualizaciu -> aktualizovat -> 4.6.2.

**Comment by jbrepogmailcom** [comment]
Ahoj, tak problém je zpátky poté, co jsem přeinstaloval KODI, mám v 18 (v 19 je shit!). I když jsem downgradoval na beautifulsoup 4.6.2 tak mi mall.cz verze 0.16 dává tuto chybu:

2022-09-08 21:02:33.172 T:2372571968 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
2022-09-08 21:02:33.181 T:2372571968  NOTICE: [kodiswift] Request for "/video/%2Fudalosti-ludka-stanka%2Fvevodkyne-meghan-zaziva-nejvetsi-peklo-na-zemi-cely-svet-ji-zesmesnuje-a-hazi-ji-klacky-pod-nohy" matches rule for function "video"
2022-09-08 21:02:34.082 T:3011151232   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2Fudalosti-ludka-stanka%2Fvevodkyne-meghan-zaziva-nejvetsi-peklo-na-zemi-cely-svet-ji-zesmesnuje-a-hazi-ji-klacky-pod-nohy]

**Comment by kapitan-iglu** [comment]
Podla logu je problem s kodiswift, skus skontrolovat aj jeho verziu, vid text v [predchadzajucom prispevku](https://github.com/koudi/plugin.video.mall.tv/issues/19#issuecomment-821794481).

Chcel som to zreprodukovat s kodi18 na dvoch windows PC ale ani na jednom si nevedelo kodi nainstalovat potrebne zavislosti z jeho vlastneho repozitara...

**Comment by jbrepogmailcom** [comment]
Dost mě to žere, že nejsem schopen rozchodit co fungovalo. Dalo mi dost práce najít kodiswift jako zip, protože v add-ons v KODI jsem to nemohl najít. Nainstaloval jsem verzi 0.0.11 z https://kodi.tv/addons/leia/script.module.kodiswift , ale pořád mi to hází chybu unicode:
```
2022-09-12 22:10:14.517 T:2142200640 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
2022-09-12 22:10:14.528 T:2142200640  NOTICE: [kodiswift] Request for "/video/%2Fudalosti-ludka-stanka%2Fputin-je-pry-taky-jen-clovek-cte-motivacni-citaty-a-pripravuje-se-na-hudebni-vystoupeni-v-metru" matches rule for function "video"
2022-09-12 22:10:15.483 T:3011904896   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2Fudalosti-ludka-stanka%2Fputin-je-pry-taky-jen-clovek-cte-motivacni-citaty-a-pripravuje-se-na-hudebni-vystoupeni-v-metru]
```
