### ISSUE TITLE
Některé videa nelze přehrát

### ISSUE THREAD

**Issue by lama18** [koudi/plugin.video.mall.tv#2]
Nezjistil jsem jaké, zdá se, že random.
+ Zároveň nelze otevřít kategorii Nejnovější.

**Android TV & Kodi 17.6**

`18:54:04.626 T:2071988512  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
18:54:05.274 T:2071988512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
18:54:05.497 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
18:54:05.501 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
18:54:07.955 T:2076436768  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
18:54:08.561 T:2076436768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
18:54:08.751 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
18:54:08.755 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
18:54:12.218 T:2076719392  NOTICE: [kodiswift] Request for "/popular/0" matches rule for function "paged_videos"
18:54:22.543 T:2077227296  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
18:54:23.134 T:2077227296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
18:54:23.315 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
18:54:23.317 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
18:54:41.421 T:2077227296  NOTICE: [kodiswift] Request for "/category" matches rule for function "category_index"
18:54:41.996 T:2077227296 WARNING: [plugin.video.mall.tv] plugin://plugin.video.mall.tv/category/3
18:54:45.658 T:2077227296  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
18:54:46.227 T:2077227296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
18:54:46.431 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
18:54:46.434 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
18:54:49.055 T:2076182816  NOTICE: [kodiswift] Request for "/popular/0" matches rule for function "paged_videos"
18:55:06.833 T:2070006048  NOTICE: [kodiswift] Request for "/video/%2F2-neusnout-pri-peceni-pizzy" matches rule for function "video"
18:55:10.663 T:2070006048 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
18:55:10.668 T:2070006048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 26, in video
                                                url = api.get_video_url(link)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 159, in get_video_url
                                                selected = filter(lambda x: x <= max_quality, qualities)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:55:10.956 T:18446744072184400160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2F2-neusnout-pri-peceni-pizzy]
18:55:14.447 T:2069829920  NOTICE: [kodiswift] Request for "/video/%2Fvolby-skoncily-a-jestli-nemate-radi-andreje-babise-tak-si-dejte-pozor-2" matches rule for function "video"
18:55:15.348 T:2069829920 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
18:55:15.494 T:18446744072184400160  NOTICE: VideoPlayer: Opening: https://kadare.gjirafa.com/api/media/malltv/t0zz10/1080/index.m3u8
18:55:15.495 T:18446744072184400160 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:55:15.530 T:2069829920  NOTICE: Creating InputStream
18:55:15.565 T:2069829920  NOTICE: Creating Demuxer
18:55:19.184 T:2069829920  NOTICE: Opening stream: 0 source: 256
18:55:19.185 T:2069829920  NOTICE: Creating video codec with codec id: 28
18:55:20.015 T:2069829920  NOTICE: Creating video thread
18:55:20.017 T:2069829920  NOTICE: Opening stream: 1 source: 256
18:55:20.020 T:2069829920  NOTICE: Finding audio codec for: 86018
18:55:20.022 T:2059356448  NOTICE: running thread: video_thread
18:55:20.026 T:2069829920  NOTICE: Creating audio thread
18:55:20.030 T:2058311968  NOTICE: running thread: CVideoPlayerAudio::Process()
18:55:20.051 T:2058311968  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
18:55:20.073 T:18446744071777671456  NOTICE: Trying to open: 48000 samplerate 12 channelMask 4 encoding
18:55:20.087 T:18446744071777671456  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 65600 m_frames: 4100 m_frameSize: 8 channels: 2
18:55:22.123 T:18446744072184400160  NOTICE: Using GL_TEXTURE_2D
18:55:22.135 T:18446744072184400160  NOTICE: GL: Using MediaCodec (Surface) render method
18:55:22.135 T:18446744072184400160  NOTICE: GL: NPOT texture support detected
18:55:22.712 T:2059356448 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
18:55:27.685 T:18446744072184400160 WARNING: Previous line repeats 3 times.
18:55:27.685 T:18446744072184400160   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
18:55:32.493 T:2048911648  NOTICE: [kodiswift] Request for "/video/%2F5-skryt-smradlave-ponozky" matches rule for function "video"
18:55:38.346 T:2048911648 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
18:55:38.349 T:2048911648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 26, in video
                                                url = api.get_video_url(link)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 159, in get_video_url
                                                selected = filter(lambda x: x <= max_quality, qualities)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
18:55:38.588 T:18446744072184400160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2F5-skryt-smradlave-ponozky]
18:55:38.607 T:18446744072184400160  NOTICE: CVideoPlayer::CloseFile()
18:55:38.608 T:18446744072184400160  NOTICE: VideoPlayer: waiting for threads to exit
18:55:38.612 T:2069829920  NOTICE: CVideoPlayer::OnExit()
18:55:38.612 T:2069829920  NOTICE: Closing stream player 1
18:55:38.612 T:2069829920  NOTICE: Waiting for audio thread to exit
18:55:38.633 T:2058311968  NOTICE: thread end: CVideoPlayerAudio::OnExit()
18:55:38.633 T:2069829920  NOTICE: Closing audio device
18:55:38.753 T:2069829920  NOTICE: Deleting audio codec
18:55:38.754 T:2069829920  NOTICE: Closing stream player 2
18:55:38.754 T:2069829920  NOTICE: waiting for video thread to exit
18:55:38.755 T:18446744071777671456  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
18:55:38.759 T:18446744071777671456  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 3770 m_frameSize: 8 channels: 2
18:55:38.799 T:2059356448  NOTICE: thread end: video_thread
18:55:38.800 T:2069829920  NOTICE: deleting video codec
18:55:38.916 T:18446744072184400160  NOTICE: VideoPlayer: finished waiting
18:55:38.917 T:18446744072184400160  NOTICE: CVideoPlayer::CloseFile()
18:55:38.918 T:18446744072184400160  NOTICE: VideoPlayer: waiting for threads to exit
18:55:38.920 T:18446744072184400160  NOTICE: VideoPlayer: finished waiting
18:58:49.571 T:18446744072184400160   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
18:58:52.743 T:2043975968  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
18:58:53.280 T:2043975968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
18:58:53.492 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
18:58:53.496 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
19:00:07.408 T:18446744072184400160   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
19:00:34.933 T:18446744072184400160  NOTICE: VideoPlayer: Opening: http://ivys-st01-2.o2tv.cz/atip/43b894e900b21af2a19190507254a332/1539882034126/61924494877503495-pc.m3u8
19:00:34.934 T:18446744072184400160 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:00:34.948 T:18446744071638026528  NOTICE: Creating InputStream
19:00:35.022 T:18446744071638026528  NOTICE: Creating Demuxer
19:00:36.748 T:18446744071638026528  NOTICE: Opening stream: 6 source: 256
19:00:36.748 T:18446744071638026528  NOTICE: Creating video codec with codec id: 28
19:00:37.166 T:18446744071638026528  NOTICE: Creating video thread
19:00:37.167 T:2076182816  NOTICE: running thread: video_thread
19:00:37.169 T:18446744071638026528  NOTICE: Opening stream: 7 source: 256
19:00:37.170 T:18446744071638026528  NOTICE: Finding audio codec for: 86018
19:00:37.173 T:18446744071638026528  NOTICE: Creating audio thread
19:00:37.175 T:2064648480  NOTICE: running thread: CVideoPlayerAudio::Process()
19:00:37.178 T:2064648480  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
19:00:37.222 T:18446744071777671456  NOTICE: Trying to open: 48000 samplerate 12 channelMask 4 encoding
19:00:37.237 T:18446744071777671456  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 48000 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 65600 m_frames: 4100 m_frameSize: 8 channels: 2
19:00:37.245 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.ivysilani/?play=218452801081018
19:00:37.252 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ivysilani/?play=218452801081018) failed
19:00:38.037 T:18446744072184400160  NOTICE: Using GL_TEXTURE_2D
19:00:38.054 T:18446744072184400160  NOTICE: GL: Using MediaCodec (Surface) render method
19:00:38.055 T:18446744072184400160  NOTICE: GL: NPOT texture support detected
19:00:38.565 T:2076182816 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:09:17.275 T:18446744072184400160 WARNING: Previous line repeats 6 times.
19:09:17.276 T:18446744072184400160  NOTICE: CVideoPlayer::CloseFile()
19:09:17.276 T:18446744072184400160  NOTICE: VideoPlayer: waiting for threads to exit
19:09:17.283 T:18446744071638026528  NOTICE: CVideoPlayer::OnExit()
19:09:17.284 T:18446744071638026528  NOTICE: Closing stream player 1
19:09:17.284 T:18446744071638026528  NOTICE: Waiting for audio thread to exit
19:09:17.313 T:2064648480  NOTICE: thread end: CVideoPlayerAudio::OnExit()
19:09:17.314 T:18446744071638026528  NOTICE: Closing audio device
19:09:17.336 T:18446744071638026528  NOTICE: Deleting audio codec
19:09:17.336 T:18446744071638026528  NOTICE: Closing stream player 2
19:09:17.337 T:18446744071638026528  NOTICE: waiting for video thread to exit
19:09:17.338 T:18446744071777671456  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
19:09:17.344 T:18446744071777671456  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 3770 m_frameSize: 8 channels: 2
19:09:17.352 T:2076182816  NOTICE: thread end: video_thread
19:09:17.354 T:18446744071638026528  NOTICE: deleting video codec
19:09:17.487 T:18446744072184400160  NOTICE: VideoPlayer: finished waiting
19:09:17.570 T:18446744072184400160  NOTICE: CVideoPlayer::CloseFile()
19:09:17.570 T:18446744072184400160  NOTICE: VideoPlayer: waiting for threads to exit
19:09:17.570 T:18446744072184400160  NOTICE: VideoPlayer: finished waiting
19:09:17.570 T:18446744072184400160  NOTICE: CVideoPlayer::CloseFile()
19:09:17.571 T:18446744072184400160  NOTICE: VideoPlayer: waiting for threads to exit
19:09:17.571 T:18446744072184400160  NOTICE: VideoPlayer: finished waiting
19:09:22.389 T:18446744072184400160  NOTICE: GL_VENDOR = ARM
19:09:22.391 T:18446744072184400160  NOTICE: GL_RENDERER = Mali-T624
19:09:22.392 T:18446744072184400160  NOTICE: GL_VERSION = OpenGL ES 3.1 v1.r14p0-01rel0.6b74fe029eb9036e17fbbd931e0471db
19:09:22.392 T:18446744072184400160  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
19:09:22.393 T:18446744072184400160  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image
19:09:24.817 T:18446744071777671456  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
19:09:24.831 T:18446744071777671456  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 3770 m_frameSize: 8 channels: 2
19:09:34.423 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.ivysilani/?menu=byDate
19:09:34.425 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ivysilani/?menu=byDate) failed
19:09:36.977 T:18446744072184400160   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
19:09:38.233 T:1861462304  NOTICE: [kodiswift] Request for "/" matches rule for function "index"
19:09:41.336 T:1861462304  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"
19:09:41.905 T:1861462304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 33, in paged_videos
                                                items = api.get_paged_videos(page, video_type)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 92, in get_paged_videos
                                                videos = self.extract_videos(page, search_section=(page == 0))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 127, in extract_videos
                                                'duration': self.get_duration(card.find('span', {'class': 'badge__wrapper-video-duration'}).text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--
19:09:42.097 T:18446744072184400160   ERROR: GetDirectory - Error getting plugin://plugin.video.mall.tv/recent/0
19:09:42.100 T:18446744072184400160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mall.tv/recent/0) failed
19:10:02.247 T:1861462304  NOTICE: [kodiswift] Request for "/popular/0" matches rule for function "paged_videos"
19:10:11.216 T:1850210592  NOTICE: [kodiswift] Request for "/video/%2F1-dostat-druhou-sanci" matches rule for function "video"
19:10:15.945 T:1850210592 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value
19:10:15.950 T:1850210592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 63, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/addon.py", line 26, in video
                                                url = api.get_video_url(link)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mall.tv/mall.py", line 159, in get_video_url
                                                selected = filter(lambda x: x <= max_quality, qualities)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
19:10:16.134 T:18446744072184400160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mall.tv/video/%2F1-dostat-druhou-sanci]`

**Comment by koudi** [comment]
U tech nejnovejsich jde o to, ze se tam ted je live video, ktery nema stejnou strukturu jako ty ostatni. Tradicni problem scrapovani webu. Commitnul jsem rychly fix, pullni si zmeny.

U tech ostatnich video - vypada to, ze se nepovede vybrat kvalita videa. Jakou kvalitu mas v nastaveni?

**Comment by gmendrala** [comment]
Tak teď je to o hodně lepší, ze seznamu "Nejnovější" nejede např. Život je hra - pro info. Log můžu poslat. Kvalitu jsem zkoušel i snížit, ale nejde i tak.

**Comment by lama18** [comment]
#Update Kodi 18 RC

Nelze přehrát nic.

**Comment by kapitan-iglu** [comment]
Toto je uz asi neaktualne?

Teraz som vydal novu verziu, v ktorej je opravena podobna chyba. Addon sa snazil ziskat zoznam popularnych videi, ale taka kategoria uz na strankach neexistuje.

Skus ci sa objavia znovu problemy.

**Comment by lama18** [comment]
Teď už se zdá být vše ok, tehdy to byly moje Kodi začátky :-) Každopádně momentálně jsem si všiml např. u pořadu "Rozum v troubě" divné řazení Bonusů, samozřejmě, že to bude chyba i na straně Mallu, pže jednou to zařadí do hlavní kategorie pořadu a někdy do Bonusů, ale každopádně v Kodi sekce Bonusy u tohoto neodpovídají skutečnosti.
