### ISSUE TITLE
Nejdou přehrát nejnovější videa

### ISSUE THREAD

**Issue by devuserPP** [koudi/plugin.video.mall.tv#21]
verze pluginu **0.0.16**
BeautifulSoap4 **4.9.3**
Kodiswift **0.0.11**
CoreELEC **9.2.7**

chyba při vybraní "Nejnovější videa"

`2021-06-12 11:15:15.276 T:3445633920   ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.                                                     'The soupsieve package is not installed. CSS selectors cannot be used.'2021-06-12 11:15:15.871 T:3445633920 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value2021-06-12 11:15:15.888 T:3445633920  NOTICE: [kodiswift] Request for "/" matches rule for function "index"2021-06-12 11:15:17.247 T:3928638336   ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.                                                     'The soupsieve package is not installed. CSS selectors cannot be used.'2021-06-12 11:15:17.855 T:3928638336 WARNING: [kodiswift] No converter provided, unicode should be used, but returning str value2021-06-12 11:15:17.872 T:3928638336  NOTICE: [kodiswift] Request for "/recent/0" matches rule for function "paged_videos"2021-06-12 11:15:18.755 T:3928638336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                            Error Type: <type 'exceptions.NotImplementedError'>                                            Error Contents: Cannot execute CSS selectors because the soupsieve package is not installed.                                            Traceback (most recent call last):                                              File "/storage/.kodi/addons/plugin.video.mall.tv/addon.py", line 94, in <module>                                                plugin.run()                                              File "/storage/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 307, in run                                                items = self._dispatch(self.request.path)                                              File "/storage/.kodi/addons/script.module.kodiswift/lib/kodiswift/plugin.py", line 326, in _dispatch                                                resp = view_func(**items)                                              File "/storage/.kodi/addons/plugin.video.mall.tv/addon.py", line 46, in paged_videos                                                items = api.get_paged_videos(page, video_type)                                              File "/storage/.kodi/addons/plugin.video.mall.tv/mall.py", line 128, in get_paged_videos                                                videos = self.extract_videos(page, search_section=(page == 0))                                              File "/storage/.kodi/addons/plugin.video.mall.tv/mall.py", line 195, in extract_videos                                                link = card.select('.video-card__details a.video-card__details-link')[0]                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 1871, in select                                                "Cannot execute CSS selectors because the soupsieve package is not installed."                                            NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.                                            -->End of Python script error report<--`

**Comment by devuserPP** [comment]
Tak nakonec sem to vyřešil přepsáním  BeautifulSoap4 **4.9.3** =>BeautifulSoap4 **4.6.2**
Tzn. přepsal jsem `/storage/.kodi/addons/script.module.beautifulsoup4`/ obsahem souboru [script.module.beautifulsoup4-4.6.2.zip](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip) a funguje to.
Ale je to zvlášní, měl sem za to, že tento [comit #19 ,](url) to řeší, když je tam napsáno 

> Adapted to new version of BeautifulSoap4 4.9.3
